- name: Dmeo on conditional
  hosts: all
  tasks:
    - name: execute if it is centos machine
      debug:
        msg: I am centos
      when: ansible_os_family == "RedHat"

    - name: execute if it is debian machine
      debug:
        msg: I am debian
      when: ansible_os_family == "Debian"
